
package com.miguelangeljulvez.easyredsys.client.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SerClsWSEntrada", targetNamespace = "http://webservice.sis.sermepa.es")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SerClsWSEntrada {


    /**
     * 
     * @param datoEntrada
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "trataPeticionReturn", targetNamespace = "http://webservice.sis.sermepa.es")
    @RequestWrapper(localName = "trataPeticion", targetNamespace = "http://webservice.sis.sermepa.es", className = "com.miguelangeljulvez.easyredsys.ws.TrataPeticion")
    @ResponseWrapper(localName = "trataPeticionResponse", targetNamespace = "http://webservice.sis.sermepa.es", className = "com.miguelangeljulvez.easyredsys.ws.TrataPeticionResponse")
    public String trataPeticion(
            @WebParam(name = "datoEntrada", targetNamespace = "http://webservice.sis.sermepa.es")
            String datoEntrada);

    /**
     * 
     * @param datoEntrada
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "consultaDCCReturn", targetNamespace = "http://webservice.sis.sermepa.es")
    @RequestWrapper(localName = "consultaDCC", targetNamespace = "http://webservice.sis.sermepa.es", className = "com.miguelangeljulvez.easyredsys.ws.ConsultaDCC")
    @ResponseWrapper(localName = "consultaDCCResponse", targetNamespace = "http://webservice.sis.sermepa.es", className = "com.miguelangeljulvez.easyredsys.ws.ConsultaDCCResponse")
    public String consultaDCC(
            @WebParam(name = "datoEntrada", targetNamespace = "http://webservice.sis.sermepa.es")
            String datoEntrada);

}
